<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.12">
  <POU Name="FC1" Id="{937363ea-ad41-4b81-afaf-d5c68b6c65ee}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM FC1
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FC1">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>