<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.12">
  <POU Name="FC2" Id="{6d3fc48b-8611-4990-8b52-215656a9b975}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM FC2
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FC2">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>