<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.12">
  <POU Name="FC3" Id="{0e42956f-4f7f-45d6-9596-8a90c0d9b087}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM FC3
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FC3">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>