<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.12">
  <POU Name="MAIN" Id="{47e8557a-6eab-4ae9-9092-a5cfa54c2ff8}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
  test :INT;
  test1 :INT;
  test2 :INT;
  test3 :INT;
  test4 :INT;
END_VAR

    ]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>